version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: yt_mp3_dev
    ports:
      - '3001:3001'
    volumes:
      - .:/app
      - ./cookies.txt:/tmp/cookies.txt
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
      - YOUTUBE_COOKIES_PATH=/tmp/cookies.txt
    restart: unless-stopped